type PowerFuture {
   closePrice: Float,
   type: String!,
   product: String!,
   year:  String,
   quarter: String,
   month: String
}

type PowerSpot {
   datetime: String! @unique(index: "power_spot_datetime")
   price: Float
}

type EndCustomerRate {
   date: String!
   zipcode: String
   consumption: Int
   loadProfile: String
   grossHourlyRate: Float
   grossBaseRate: Float
   netHourlyRate: Float
   netBaseRate: Float
   immediateBonus: Float
   newCustomerBonus: Float
}


type PowerSpotForecast {
   datetime: String! @unique(index: "power_spot_forecast_datetime")
   price: Float
}

type Query {
   allPowerFutures: [PowerFuture!]
   allPowerSpots: [PowerSpot!]
}
