type PowerFuture {
   tradeTime: Time!
   tradePrice: Float
   closePrice: Float
}

type PowerSpot {
   datetime: String! @unique(index: "power_spot_datetime")
   price: Float
}


type PowerSpotForecast {
   datetime: String! @unique(index: "power_spot_forecast_datetime")
   price: Float
}

type Query {
   allPowerFutures: [PowerFuture!]
   allPowerSpots: [PowerSpot!]
}
