# This is a basic workflow to help you get started with Actions

name: Votes

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
    - 'src/vote.py'
      
    branches:
      - master

  schedule:
  - cron: "*/11 * * * *"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    container: ragnorc/iuppiter
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run vote.py
      run: python $GITHUB_WORKSPACE/src/vote.py
      env: # Or as an environment variable
        FAUNA_SECRET: ${{ secrets.FAUNA_SECRET }}
